### PR TITLE
Add contact us page

### PR DESCRIPTION
**Pull request by tonytan4ever**

### CODE REVIEW

**Comment by acj3rd** [comment]
I'd like to see some unit tests added before this is merged to master.

**Comment by acj3rd** [comment]
I just found the unit tests. How is the code coverage?

**Comment by tonytan4ever** [comment]
@acj3rd: With the latest test,  ContactUs view and form are covered 100%.
I haven't unit-tested SendmailEmailBackend.py yet,  as we haven't decided which email backend to use,  that file may end up being deleted.

**Comment by tonytan4ever** [comment]
Right now the user email filter has a basic validation.  The Other fields are free text.
Any specific requirement on user input sanitization?

**Comment by tonytan4ever** [comment]
Added XSS sanitization.

**Pull request merged**
