### PR TITLE
cameron-chc-353-improve-look-transcription-states

### PR DESCRIPTION
**Pull request by cameroneshgh**
Transcription status message has been moved above the contribute box with a color-coded set of state icons. Also, the buttons underneath the contribute box have been reorganized horizontally.

### CODE REVIEW

**Comment by acj3rd** [comment]
As anonymous user, when clicking "Save" the captcha shows up but it pushed the switches into the image being transcribed. See screen shot below.

screen shot 2018-08-27 at 5 07 50 pm

**Comment by acj3rd** [comment]
In my comment above, the Submit for Review button is active when the captcha is rendered. When a user clicks it, the transcription is lost.

**Comment by elainekamlley** [comment]
@cameroneshgh Could we move the contact manager button to the bottom right corner? I think it will add more space to the action buttons.

**Comment by cameroneshgh** [comment]
All requested changes have been made. Ready for review, with contact button placement addressed.

**Comment by cameroneshgh** [comment]
The visibility of the save button has been fixed. The issue of the former is a bug fix, I believe. There's a little more in-depth work that needs to be done in how submit is handled when a user is not signed in.

**Comment by elainekamlley** [comment]
Okay, I logged the submit issue as a bug https://artemisconsulting.atlassian.net/browse/CHC-413

I think this is good to merge

**Comment by acj3rd** [comment]
Reviewing on my AWS instance. Issues:
1. After the Asset has been "Completed", future edits can not be made. Also, Tags can't be added when in Completed state since the Save button is not available. Is this the desired behavior?
2. When on the Project page of a collection, the Project name is not seen, just the collection name.
3. After clicking the Tags button on an asset, the user is correctly redirected to the Tags tab. If the user clicks Transcription and saves, the user is redirected to the Tags tab. They should stay on the Transcription tab.
4. When a user clicks the Plus (+) button on the image to magnify, then submits a transcription or Tag, the image is redrawn with no magnification. The magnification should stay at the same level as when the Save button is hit.
5. As anonymous user, when clicking Save and the CAPTCHA widget appears, the Submit for Review is still active. If the user clicks this button while the CAPTCHA is present, they lose any transcription work they entered and the asset is in "Submitted for Review" state. The Submit for Review should not be selectable when the CAPTCHA is viewable. 
6. When displaying an asset for transcription/tag, the "Collections" button on bottom of screen goes nowhere.
7. On the front page, the COLLECTION link at bottom of page goes nowhere.
8. On Transcription/Tags page, the breadcrumbs have 2 entries, with what looks like the collection name and a string with characters and numbers. 
   Issues with the breadcrumbs:
   A. They don't reflect the full path to the transcription page. The first entry has a collection name, but there is no Project name.
   B. The final item on the breadcrumb is not clickable, this is not a problem. However, as a user, I don't understand what a character string with numbers means. For example, in this breadcrumb, "Go back to Rosa Parks > mss859430178", what does mss859430178 mean?
   C. Breadcrumbs should include the Project so the user doesn't have to click out to collection then click into the Project. The user should have a direct link to the project.

**Comment by acj3rd** [comment]
Just built using latest code from cameron-chc-353-improve-look-transcription-states, server error when clicking Transcribe or Tag. Test on http://18.191.198.80/transcribe/rosa-parks/rp/

**Comment by elainekamlley** [comment]
All of these are bugs and refinement of the transcription process. I've logged some of these in the past but the rest need to be tickets. Completely outside the scope of this PR. 

For number 1, yes that is a desired function. The save button brings the completed transcription back into editing state. I didn't realize that save was also connected to tags. We need to separate tag save and transcription save or have a solution that save is only available for tags after a transcription is complete. 

Lets fix the server issue and get this merged

**Comment by cameroneshgh** [comment]
@acj3rd, it's fixed. I messed it up with whatever I was trying to do with the breadcrumb—stupidly trying to do two things at once.

**Comment by acj3rd** [comment]
1. As anonymous user click Submit for Review. CAPTCHA shows up, correct captcha string entered, proper green alert showing Success, but the transcription stays in Edit.
2. When clicking the Contact a Manager button, there is no effect. It does does nothing.

**Comment by acj3rd** [comment]
Clicking Contact a Manger button generates a Server Error

**Comment by acj3rd** [comment]
Click Contact Manager works. PR Approved, reminder to pay attention to the merge with the 5 conflicted files

**Pull request merged**
