### PR TITLE
Refactor data model for campaign / project / item /asset

### PR DESCRIPTION
**Pull request by rstorey**
There's some work to be done to implement web services to get items in a project. You can see in the views where it uses the old style code instead of the REST API.

Addresses CHC-383 and CHC-415 and half of CHC-364

### CODE REVIEW

**Comment by elainekamlley** [comment]
Tested functionality on the aws branch: 

Looks good: 
- The URL 👍 
- Nesting of campaign/projects/items 👍 

here's what I found:  
- When I imported a rosa parks collection and added a year in the project name ie `1955` there was a import error. The page was in a reload loop and the red error message looked like it was flashing
- When I added date range `1955 - 1956` it gave a 404 error. The URL path generated dashes and because there is a dash in the date it created double dash. I did however, used the word `to` ie 1955 to 1956` and that worked to build the URL. 
- Noticed that the publish button was missing. I can see the collection from the admin side but can't see it as a anonymous or registered user. 
- When I imported a new project the image for the item was missing when I, not sure if you included that ticket in this PR. I did see your image for the item that was already there.

**Comment by rstorey** [comment]
The first problem you found is pre-existing. It needs to be ticketed and fixed outside of this work. Import by collection / search result URL was / is also broken.
Working on Issue 2 and 3 now.
The image selection bit for the item thumbnail I was planning to complete in CHC-364. The way it works now, you can use the Django admin to set the thumbnail URL for an item manually (that's how I got the one to show up). Need to add a bit of code to the importer to automatically select the thumbnail image and populate the URL field.

**Comment by rstorey** [comment]
The publish button was missing because of the way I created the admin user - it needed to be added to the CM group. It shows up now.

**Comment by rstorey** [comment]
As far as the dash issue goes: I was able to use a dash in the project name, as long as it's not surrounded by spaces. Example: http://ec2-18-212-95-158.compute-1.amazonaws.com/campaigns/rosa-parks/books-owned-1866-2001/mss859430374/

**Pull request merged**
