### PR TITLE
cameron-chc-300-indicators-completed-tasks

### PR DESCRIPTION
**Pull request by cameroneshgh**
[http://ec2-34-226-136-126.compute-1.amazonaws.com](url)

### CODE REVIEW

**Comment by elainekamlley** [comment]
Indicators show up and look good only when I am logged in. Does not happen when I am an anonymous user. 

Also, I was able to approve my own transcription as complete when logged in and then able to bring it back into open for transcription by hitting save. Seems like the permissions are not enforced.

**Comment by cameroneshgh** [comment]
Fixed the "Only registered users can tag" display issue and showing confirmation messages for unregistered users.

**Comment by cameroneshgh** [comment]
I've addressed the recurrence of the indicator message ( = is not the same as == is not the same as === ). I think we can address the anonymous user being able to submit for review with the REST API. I also disabled the tag input if the user is anonymous.

I think we're ready for review again.

**Comment by acj3rd** [comment]
Latest branch works on my AWS instance

**Pull request merged**
