### PR TITLE
Cameron chc 349 registered user profile updates

### PR DESCRIPTION
**Pull request by cameroneshgh**
Rebased with master. Made requested changes to user profile page. Updated jQuery integrity hash.

Includes CHC-425, CHC-427, CHC-428, CHC-430, CHC-431, CHC-432, CHC-433, CHC-434, and CHC-435.

http://ec2-34-226-136-126.compute-1.amazonaws.com/

### CODE REVIEW

**Comment by cameroneshgh** [comment]
@acj3rd 2 is in FAQ branch. Working on 1

**Comment by cameroneshgh** [comment]
Removing CHC-429 from inclusion in this ticket. Anonymous users can save. SfR is part of other bug tickets.

**Comment by acj3rd** [comment]
As community manager, when publishing a project, the alert dialog button doesn't do anything. Also, I can't read the text in the alert dialog.

**Comment by timpandrews** [comment]
Looks good for the most part.  I agree with Drew about the white text on the light background.  You have white text in the footer and the publish confirmation pop ups.  @cameroneshgh does this get fixed in the next PR?

**Comment by tonytan4ever** [comment]
Looks good to me as well.   If other issues can be solved in another PR we can merge this first ?

**Comment by elainekamlley** [comment]
Will be going through each ticket to test. Will check off if they look good. 
- [ ] CHC-425 
- [ ] CHC-427 
- [ ] CHC-428,
- [ ] CHC-430, 
- [ ] CHC-431, 
- [ ] CHC-432, 
- [ ] CHC-433, 
- [ ] CHC-434, 
- [ ] CHC-435.
- [ ] CHC-349

**Comment by elainekamlley** [comment]
When the page is smaller and the hamburger nav is visible, when I click on `About` page the Login and Registered options are gone

**Comment by elainekamlley** [comment]
Save for a tag doesn't work

**Comment by elainekamlley** [comment]
CHC 349 - The Username and Email should be static and not look like an editable form. At launch only community managers can change an email or username. The only thing that users can do is change their password

**Comment by elainekamlley** [comment]
Looks good from my end. Nice work.

**Pull request merged**
